### PR TITLE
File structure Restored

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
Renames landing page as index.html 
Make previous index page to home page (redirected by index page) and put it in pages folder
Created scripts folder and put all js file in it
properly link all pages CSS and js

image

### CODE REVIEW

**Comment by codervivek5** [comment]
bro kindly solve merge conflict

**Comment by AK-shat-JAIN** [comment]
Sr solve conflict button is not active at my end can you guide me on how to do so
image

**Comment by codervivek5** [comment]
At this time I am not in home ......I will see you at evening time.

**Review by codervivek5 — APPROVED** [review]

**Comment by AK-shat-JAIN** [comment]
Ok sr thanks

**Pull request closed without merging**
