### PR TITLE
Added full name and OTP button in login page

### PR DESCRIPTION
**Pull request by priyanka1551**
#50

### CODE REVIEW

**Comment by codervivek5** [comment]
Send any screenshot so that I can review

**Comment by priyanka1551** [comment]
> Send any screenshot so that I can review

Screenshot (132)

**Comment by codervivek5** [comment]
Perfect....last one thing.
Kindly add this page to login button which is in home page

**Comment by priyanka1551** [comment]
> Perfect....last one thing. Kindly add this page to login button which is in home page

I had already added and make the pr after that

**Comment by codervivek5** [comment]
Okay

**Comment by codervivek5** [comment]
Okay

**Pull request merged**
