### PR TITLE
Responsiveness added to Contact Us page

### PR DESCRIPTION
**Pull request by pooranjoyb**
## Description

With this enhancement, the `Contact Us` page is made responsive.

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've made the enhancement both for light as well as dark modes
- [x] I ensured that the page remains responsive after the addition of the custom CSS

## Related Issues or Pull Requests

#117 

## Add relevant screenshot or video (if any)

[demo.webm](https://user-images.githubusercontent.com/90945182/221368368-35d76763-7885-478b-af36-579abf21ff85.webm)

### CODE REVIEW

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
remove the image for mobile view and make menu as side drawer

**Comment by pooranjoyb** [comment]
> remove the image for mobile view and make menu as side drawer

Ok sure.. :)

**Comment by codervivek5** [comment]
send me output after done :)

**Comment by pooranjoyb** [comment]
## Demo Output

[demo2.webm](https://user-images.githubusercontent.com/90945182/221372384-0162c4a5-b030-4454-b449-dc4dbc3dd77b.webm)

## Here is the required output. Hope you like it :) @codervivek5

**Comment by codervivek5** [comment]
dude....remove svg image in mobile view but not in desktop view

**Comment by pooranjoyb** [comment]
Give me a minute. @codervivek5

**Comment by codervivek5** [comment]
ok
after done show me output

**Comment by pooranjoyb** [comment]
Here's the demo 

[Video-Sun-Feb-26-2023-23-32-07.webm](https://user-images.githubusercontent.com/90945182/221428000-e1c81dcd-f941-46fe-88c0-cecd2b9fcb82.webm)

**Comment by codervivek5** [comment]
A last change if you can......make login button same as other option in mobile view in menu

**Comment by pooranjoyb** [comment]
Yeah sure, why not, please wait for few more mins, coming new changes. :) @codervivek5

**Comment by codervivek5** [comment]
IN mobile view that is not looking good :(

**Comment by pooranjoyb** [comment]
Screenshot

sc

**Pull request merged**
