### PR TITLE
made changes in#25

### PR DESCRIPTION
**Pull request by bhavya321321**
image1234
this change in #25

### CODE REVIEW

**Comment by bhavya321321** [comment]
changes done in issue#25

**Comment by bhavya321321** [comment]
image12
sir like this

**Comment by codervivek5** [comment]
Yeas looking pretty good but kindly remove colour background and add any simple background which is related to home page

**Comment by bhavya321321** [comment]
ok sir

**Comment by codervivek5** [comment]
share any screenshot

**Comment by bhavya321321** [comment]
please review sir

**Comment by bhavya321321** [comment]
any changes sir please tell if needed

**Pull request merged**
