### PR TITLE
Footer enhancement

### PR DESCRIPTION
**Pull request by ritika728**
Hey, I have resolved issue #65 under JWOC. Here is the video of the changes made:

https://user-images.githubusercontent.com/91181981/219880142-f7416867-9005-4214-a507-026267811fab.mp4

### CODE REVIEW

**Comment by codervivek5** [comment]
can you add my social media handles ??

**Comment by codervivek5** [comment]
also replace G+ to YouTube

**Comment by codervivek5** [comment]
FACEBOOK - https://www.facebook.com/codervivek

**Comment by ritika728** [comment]
Done! Kindly review @codervivek5

**Comment by codervivek5** [comment]
if you send me screenshot then i will review

**Comment by ritika728** [comment]
Here is the video:
https://user-images.githubusercontent.com/91181981/219882006-45a818cd-2be2-4c42-8150-ae1eab3aa7d6.mp4

**Comment by codervivek5** [comment]
perfect..🙂

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
