### PR TITLE
enhanced cart page

### PR DESCRIPTION
**Pull request by Neha00011**
I have changed the UI of the page and tried to make it better.
here is the output.
Kindly merge the pr.
Screenshot (69)

### CODE REVIEW

**Comment by codervivek5** [comment]
Make it center and change background color with reference to home page color and provide little margin in every box

**Comment by Neha00011** [comment]
Ok

**Comment by Neha00011** [comment]
Screenshot (70)
@codervivek5 is it ok now?

**Comment by codervivek5** [comment]
Ads some background color and top margin

**Comment by Neha00011** [comment]
Screenshot (71)
any more changes required or I can creat a PR now?

**Comment by codervivek5** [comment]
I am also talking about white areas....no worry...
Kindly make its position center from top then I will merge you PR

**Comment by Neha00011** [comment]
Ok I will do that.

**Pull request closed without merging**
