### PR TITLE
Isuue  #63

### PR DESCRIPTION
**Pull request by SarveshGholap**
Files and folder structure updated

### CODE REVIEW

**Comment by codervivek5** [comment]
Kindly solve merge conflict

**Comment by SarveshGholap** [comment]
solved merge conflicts

**Comment by codervivek5** [comment]
kindly solve the merge conflict

**Comment by SarveshGholap** [comment]
isuue 63 solved

**Comment by codervivek5** [comment]
kindly use proper Issue number at the PR time

**Comment by codervivek5** [comment]
means make your PR correaspomding that issue

**Comment by SarveshGholap** [comment]
issue #63 #81 files and folder structure

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
