### PR TITLE
Fevicon zoomed in and added

### PR DESCRIPTION
**Pull request by ritika728**
I have resolved issue #105 under JWOC. 
Have updated the fevicon on all the pages like this one.
photo

### CODE REVIEW

**Comment by ritika728** [comment]
@codervivek5 please review

**Comment by codervivek5** [comment]
can you share a link so that I can review your PR

**Comment by ritika728** [comment]
Here is the video
https://user-images.githubusercontent.com/91181981/221271534-4b80af1a-8de5-45a7-a851-a8c18ee0e151.mp4

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Thankyou for contribution :)

**Pull request merged**
