### PR TITLE
Enhance login page and Improvised the UI

### PR DESCRIPTION
**Pull request by Monishparameswaran**
Added the login page with interactive UI
Cleared linking bugs
added color palettes to improve the design

### CODE REVIEW

**Comment by codervivek5** [comment]
send screenshot for review

**Comment by Monishparameswaran** [comment]
FormFilgit

**Comment by codervivek5** [comment]
Below to login button give option for registration also. So that use can register yourself if not done.

**Comment by Monishparameswaran** [comment]
UpdatedFinalForm

**Comment by Monishparameswaran** [comment]
@codervivek5 Added Registration link to the login page , now it looking good, Please do Merge this.

**Comment by codervivek5** [comment]
Action login page already added...so You can Enhanced that....kindly do not make it again

**Comment by Monishparameswaran** [comment]
@codervivek5  okay, what about this login page not merged yet,.. since i have made the changes ,please merge this...!

**Comment by codervivek5** [comment]
kindly solve merge conflict

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
@Monishparameswaran kindly solve merge conflict  so that I can merge you PR

**Pull request closed without merging**
