### PR TITLE
#113 footer section

### LINKED ISSUE #113: footer section fix
there is inconsistency in footer section of different pages you can see that .i would like to fix it @codervivek5 

Screenshot (6)
Screenshot (7)
Screenshot (8)
Screenshot (9)

### PR DESCRIPTION
**Pull request by VaibhavTalkhande**
https://vaibhavtalkhande.github.io/fillform.github.io/
fix
#113 footer section
i have fixed all footer section ,built about us page ,contact and added nav to every page.

### CODE REVIEW

**Comment by codervivek5** [comment]
@VaibhavTalkhande kindly remove the testimonials option from navbar......rest of the option still on there except testimonial

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
reduced little bit size of image present in about page
image

**Comment by codervivek5** [comment]
rest of thing working properly 👍

**Comment by VaibhavTalkhande** [comment]
Should I remove form Every page

**Pull request closed without merging**
