### PR TITLE
Whichever page was active the home button was highlighted and underlined

### PR DESCRIPTION
**Pull request by ishita-singhal**

### CODE REVIEW

**Comment by codervivek5** [comment]
Can we see your output

**Comment by ishita-singhal** [comment]
Screenshot (343)
Screenshot (344)
Yes Sir

**Comment by codervivek5** [comment]
Ok send me screen shot

**Comment by ishita-singhal** [comment]
Sir, the above screenshot is of the output of the changes that I did.
Do I need to send the screen shot of the code also?

**Comment by codervivek5** [comment]
No need....now it's looking fine 🙂

**Pull request merged**
