### PR TITLE
I changed login with twitter to login with google

### PR DESCRIPTION
**Pull request by priyanka1551**
#7 
Screenshot (129)

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly solve the merge conflict then I will merge it
and try to use at PR time-specific issue which is already raised

**Comment by codervivek5** [comment]
Solve merge conflict

**Comment by codervivek5** [comment]
Can you change this UI....with two options
Login with OTP and login with Google only
Replay usr name ,password field with enter mobile number and OTP varification

**Comment by codervivek5** [comment]
If you can chage than tell me.

**Comment by priyanka1551** [comment]
> If you can change then tell me.

Okay I will complete it by tomorrow

**Comment by codervivek5** [comment]
ok

**Comment by priyanka1551** [comment]
> ok

Screenshot (130)
@codervivek5 is it fine?

**Comment by priyanka1551** [comment]
> Perfect 👍. One last Change remove password section and change user name to full name

Can I make two seperate section for first name and last name?

**Comment by codervivek5** [comment]
No only one section full name

**Comment by priyanka1551** [comment]
> No only one section full name

I am having problem in making pr please help. It got automatically closed. what to do?

**Pull request closed without merging**
