### PR TITLE
Adding a pageloadder

### PR DESCRIPTION
**Pull request by Darkrider0007**
-  Update Landing page with New UI #38
Screenshot (66)

### CODE REVIEW

**Comment by codervivek5** [comment]
make it small

**Comment by Darkrider0007** [comment]
logo?

**Comment by codervivek5** [comment]
Yes.....also solve merge conflict

**Comment by Darkrider0007** [comment]
Screenshot (67)
is this fine?

**Comment by Darkrider0007** [comment]
If everything is fine please merge this under JWOC

**Comment by Darkrider0007** [comment]
Thank You

**Pull request merged**
