### PR TITLE
Updated File Structure Properly

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
#112 issue resolved
organized files in folders (single folder for html pages, one fro CSS, and one for js) and also link them 
image

### CODE REVIEW

**Comment by codervivek5** [comment]
Perfect....is it working if convert to link....like GitHub page link....

**Comment by AK-shat-JAIN** [comment]
yes, I have run it on VS code live server

**Comment by codervivek5** [comment]
bro....solve merge conflict

**Review by codervivek5 — APPROVED** [review]

**Comment by AK-shat-JAIN** [comment]
Thanks a lot sr 🤩☺️

**Pull request merged**
