### PR TITLE
Create Dashboard page with profile

### PR DESCRIPTION
**Pull request by priyanka1551**

### CODE REVIEW

**Comment by codervivek5** [comment]
Show me output so that I can review it

**Comment by codervivek5** [comment]
@priyanka1551 can you show me output. So that I can review that

**Comment by codervivek5** [comment]
And merge you PR

**Comment by codervivek5** [comment]
And merge you PR

**Comment by priyanka1551** [comment]
> @priyanka1551 can you show me output. So that I can review that

signuppage
loginpage

**Comment by priyanka1551** [comment]
> And merge you PR

@codervivek5 I made two pr yesterday. please merge the last pr I made which is "created signup and login page and linked them#7" 
Screenshot (128)

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
