### PR TITLE
Updated README

### LINKED ISSUE #57: Updating the README
I would like to work on the README to make it more visually appealing and also add badges for tech stacks.
Some images are broken that can be fixed too.

### PR DESCRIPTION
**Pull request by the-amazing-atharva**
fixes #57

### CODE REVIEW

**Comment by codervivek5** [comment]
Use right issue number for PR

**Comment by codervivek5** [comment]
Send me output here

**Comment by the-amazing-atharva** [comment]
Issue number is correct 

Pics : 
image

.
.
image

**Comment by codervivek5** [comment]
Perfect 👍

**Comment by codervivek5** [comment]
Can you add my social media handle like LinkedIn and insta YouTube?

**Comment by the-amazing-atharva** [comment]
> Can you add my social media handle like LinkedIn and insta YouTube?

sure 
do send the links here

**Comment by codervivek5** [comment]
kindly solve merge conflic

**Comment by the-amazing-atharva** [comment]
Done , do check it now as I dont know much about resolving conflicts

**Comment by codervivek5** [comment]
Bro. kindly send me any screen shot so that I can review it then I will merge your PR

**Review by codervivek5 — APPROVED** [review]

**Pull request closed without merging**
