### PR TITLE
Added testimonial page

### PR DESCRIPTION
**Pull request by Neha00011**
I have added testimonial section .This is the output.Solved issue #102 
Screenshot (75)
Kindly add jwoc level in issue and merge the pr.

### CODE REVIEW

**Comment by codervivek5** [comment]
kindly increase width little bit more.......your work is amazing👏👏

**Comment by codervivek5** [comment]
also change the color according to website

**Comment by Neha00011** [comment]
Ok I will do the changes by tomorrow.

**Comment by Neha00011** [comment]
I have changed the color according to the home page and increased the width. This is the output.
Screenshot (76)
Kindly merge the pr and before merging, add JWOC tag in the issue and pr both.

**Comment by codervivek5** [comment]
perfect

**Review by codervivek5 — APPROVED** [review]

**Comment by codervivek5** [comment]
Thankyou for contribution

**Comment by Neha00011** [comment]
Thank you

**Pull request merged**
