### PR TITLE
Add about us page

### PR DESCRIPTION
**Pull request by KrishnaTheCoder756**
Inform me if anything else needs to be added

### CODE REVIEW

**Comment by KrishnaTheCoder756** [comment]
Was it assigned to me? I can't find any information regarding that. By the way, I know the issue number I commented on. Can you please tell What should I do now?

**Comment by codervivek5** [comment]
if you do any changes or any thing then show me output
as screenshot and connect with us in discord

**Comment by KrishnaTheCoder756** [comment]
Can I please get the discord link?

**Comment by codervivek5** [comment]
I will share that.

**Comment by KrishnaTheCoder756** [comment]
Hello! I haven't received it yet. Have you shared it anywhere?

**Comment by codervivek5** [comment]
Just wait

**Comment by codervivek5** [comment]
https://discord.gg/8zGnu4YE

**Pull request closed without merging**
