### PR TITLE
Create Logo #5

### LINKED ISSUE #5: Create Logo

### PR DESCRIPTION
**Pull request by codingis4noobs2**
Replaced the new logo with old logo. Fixes #5

### CODE REVIEW

**Comment by codervivek5** [comment]
send me image of logo so that I can review that.

**Comment by codervivek5** [comment]
make your pr with exact PR number so that I can merger it under the policy of JWOC

**Comment by codingis4noobs2** [comment]
> send me image of logo so that I can review that.

logo

**Comment by codingis4noobs2** [comment]
Done @codervivek5

**Comment by codervivek5** [comment]
Have any Only one image or you create 2,3 typ of the logo?

**Comment by codingis4noobs2** [comment]
> Have any Only one image or you create 2,3 typ of the logo?

Currently only, i can create more too

**Comment by codervivek5** [comment]
Yeah create some more so that I can pick best of them

**Comment by codingis4noobs2** [comment]
logo3

what about this

**Comment by codervivek5** [comment]
Make your PR with proper issue number so that I can merge it.

**Comment by codingis4noobs2** [comment]
Done @codervivek5

**Comment by codervivek5** [comment]
I had raise a issue already with this name. You only need to mention that at the PR time.
Read all the instructions and file also comment.
You got an option at the end and mention right issue number on there

**Comment by codingis4noobs2** [comment]
Done @codervivek5

**Comment by codingis4noobs2** [comment]
Update logo with new upscaled img @codervivek5

**Comment by codingis4noobs2** [comment]
logo

**Comment by codervivek5** [comment]
Create it as high definition img like svg or vector image

**Review by codervivek5 — APPROVED** [review]

**Pull request merged**
